// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAswXUTvTOhYOH0mK4xhiGszaYC4Vokoco',
    appId: '1:586808618653:web:47cb12f7f4570a183cee74',
    messagingSenderId: '586808618653',
    projectId: 'nivaas-ac16f',
    authDomain: 'nivaas-ac16f.firebaseapp.com',
    storageBucket: 'nivaas-ac16f.firebasestorage.app',
    measurementId: 'G-PP8ZJWLVQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdpUo2KwuD7RfBju5G8YaR0rJ_l8PZEWs',
    appId: '1:586808618653:android:8ded15a8577fa1b43cee74',
    messagingSenderId: '586808618653',
    projectId: 'nivaas-ac16f',
    storageBucket: 'nivaas-ac16f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxjIU-ed-rF5-YxhTTQ522duPH_hUpmU',
    appId: '1:586808618653:ios:95fc86a5c47eebd03cee74',
    messagingSenderId: '586808618653',
    projectId: 'nivaas-ac16f',
    storageBucket: 'nivaas-ac16f.appspot.com',
    iosBundleId: 'com.juvaryatechnologies.nivaas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaxjIU-ed-rF5-YxhTTQ522duPH_hUpmU',
    appId: '1:586808618653:ios:c275f7954a562ef33cee74',
    messagingSenderId: '586808618653',
    projectId: 'nivaas-ac16f',
    storageBucket: 'nivaas-ac16f.firebasestorage.app',
    iosBundleId: 'com.nivaas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAswXUTvTOhYOH0mK4xhiGszaYC4Vokoco',
    appId: '1:586808618653:web:304094be62993ca63cee74',
    messagingSenderId: '586808618653',
    projectId: 'nivaas-ac16f',
    authDomain: 'nivaas-ac16f.firebaseapp.com',
    storageBucket: 'nivaas-ac16f.firebasestorage.app',
    measurementId: 'G-P0ZTZ8R8M4',
  );
}
